site_name: ClanGen Documentation
site_url: https://clangen.io/clangen-docs/
repo_url: https://github.com/ClanGenOfficial/clangen
repo_name: ClanGenOfficial/clangen
edit_uri: https://github.com/ClanGenOfficial/clangen-docs/edit/master/docs/
theme:
  name: material
  logo: assets/main.png
  favicon: assets/main.ico
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - navigation.top
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      scheme: clangen_light
      toggle:
        icon: material/brightness-auto
        name: Switch to ClanGen light mode

    # Palette toggle for clangen light mode
    - media: "(prefers-color-scheme: light)"
      scheme: clangen_light
      toggle:
        icon: material/weather-sunny
        name: Switch to basic light mode

    # Palette toggle for basic light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to ClanGen dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: clangen_dark
      toggle:
        icon: material/weather-night
        name: Switch to basic dark mode

    # Palette toggle for basic dark mode
    - media: "(prefers-color-scheme: og-dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
extra:
  homepage: https://clangen.io/
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

plugins:
  - search
  - git-committers:
      repository: ClanGenOfficial/clangen-docs
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - awesome-pages:
      order: asc
      sort_type: natural
      order_by: title