site_name: ClanGen Documentation
site_url: https://clangen.io/clangen-docs/
repo_url: https://github.com/ClanGenOfficial/clangen
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
plugins:
  - git-authors