site_name: ClanGen Documentation
site_url: https://clangen.io/clangen-docs/
repo_url: https://github.com/ClanGenOfficial/clangen
repo_name: ClanGenOfficial/clangen
edit_uri: https://github.com/ClanGenOfficial/clangen-docs/edit/master/docs/
nav:
  - Project Basics:
      - Project basics/development-team-roles.md
      - Project basics/getting-started-with-github-and-clangen.md
  - Code:
      - Code/index.md
      - Code/content-adding.md
  - Writing:
      - Writing/index.md
      - Writing/patrols.md
      - Writing/shortevents.md
      - Writing/leaders-den-events.md
      - Writing/thoughts.md
      - Writing/leader-ceremonies.md
      - Writing/advanced-documentation.md
  - Art:
      - Art/index.md
      - Art/cat-sprites.md
      - Art/patrol-sprites.md
      - Art/clan-symbols.md
      - Art/camp-backgrounds.md
  - Audio:
      - Audio/index.md
theme:
  name: material
  logo: assets/main.png
  favicon: assets/main.ico
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme)"
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  homepage: https://clangen.io/
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list

plugins:
  - search
  - git-committers:
      repository: ClanGenOfficial/clangen-docs
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago