name: Test Documentation Build

on:
  pull_request:
    branches:
      - development

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'   
      - name: Build documentation
        run: mkdocs build --strict
